### ISSUE TITLE
Upper body pose estimation

### ISSUE THREAD

**Issue by Abi5678** [Garfield-kh/PoseTriplet#1]
Hi, I was wondering if your model works on the wild videos of which lower body is not visible and estimated only upper body key points.

**Comment by Garfield-kh** [comment]
Hi, Thank you for the interest!

> Main

As this framework is working on self-supervised 2D-3D pose estimation, as long as you have the corresponding 2D keypoint (from detectors or label) and  RL character (with the same keypoint definition), you can train it in a self-supervised manner.
This means that this frame can be applied to **not only humans, but also [animals](https://github.com/DeepLabCut/DeepLabCut)** (e.g., [dog](https://github.com/CAMERA-Bath/RGBD-Dog), dragon, etc,) or **moving vehicles** (e.g., motorbike), **whatever contains joints**.

> Example

For example, in this paper, we have (2D body pose + RL body character), we can train a body pose estimation model.

> Upper body case

For upper body, if you have the corresponding 2D keypoint (e.g., [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose), [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose)), and RL character (with only the upper body, maybe finger included), you can try it in a self-supervised approach.
The only issue for this I think is that how to manage the root joint movement (see [example ](https://youtu.be/gHIrIPnX4G8?t=166)here), while with Leg, the RL simulator will help remove the artifacts of movement, without Leg, I think you need to add some constraints (e.g, smoothness) to ensure the plausibility of root movement as the data from RL will be used as training data for the next round.

Hope this helps,
Thank you~
