### ISSUE TITLE
Does it output BVH Motion Capture Data ?

### ISSUE THREAD

**Issue by Michaelwhite34** [Garfield-kh/PoseTriplet#13]

**Comment by Garfield-kh** [comment]
Yes, the 3D pose result from estimator is converted to BVH by [write_standard_bvh()](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/estimator/posegan_evaluate.py#L388), which is then used as reference motion for imitator.

**Comment by Michaelwhite34** [comment]
> Yes, the 3D pose result from estimator is converted to BVH by [write_standard_bvh()](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/estimator/posegan_evaluate.py#L388), which is then used as reference motion for imitator.



> Yes, the 3D pose result from estimator is converted to BVH by [write_standard_bvh()](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/estimator/posegan_evaluate.py#L388), which is then used as reference motion for imitator.

Thanks for the reply, I'll definitely try it. Another question, does it capture character position (character move around scene instead of roughly in the same place) ?

**Comment by Garfield-kh** [comment]
Yes, root trajectory is predicted in the estimator.
