### ISSUE TITLE
multi-person 3D pose estimation

### ISSUE THREAD

**Issue by dhhjx880713** [Garfield-kh/PoseTriplet#14]
Hi Gong,

we are using your impressive work for 3D pose reconstruction from video. In general, it works quite well for single-person scenarios. However, when I tried to apply it to the multi-person scenarios, it seems that it only tracks the pose for one character and tracking is not consistent on one person but jumping around on different person. So is that possible to apply for your work on multi-person 3D pose estimation? Thank you!

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
This work is focus on single person setting.
If you are interested in multi-person scenario, you may need to change **estimator ** from single person to multi person such as [ROMP](https://github.com/Arthur151/ROMP). And also for the **imitator**, you need to add more characters in the [XML ](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/assets/mujoco_models/humanoid_h36m_v5.xml#L22) file, and extra force apply in the [control](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/pose_imitation/envs/humanoid_v4.py#L338) part.

**Comment by dhhjx880713** [comment]
Thank you very much for your quick answer. We tried different SOTA approaches and your work delivers the best results for our data. I believe your work would also work fine for multi-person scenarios. I will try your suggestion for multi-person cases.

**Comment by Garfield-kh** [comment]
welcome~
You may check [mmpose](https://github.com/open-mmlab/mmpose), [mmhuman3d](https://github.com/open-mmlab/mmhuman3d) for more information about multi-person cases.
And for the imitator, the GPU-based RL [nvidia-isaac](https://developer.nvidia.com/isaac-gym) is much faster compared with current mujoco simulator.
