### ISSUE TITLE
About custom training and inference

### ISSUE THREAD

**Issue by PGogo** [Garfield-kh/PoseTriplet#15]
感谢作者的优秀工作，并且在这分享实现给大家！
我刚刚看了你的视频演讲回放，讲得很棒！
我正在做3D pose的应用，有一些问题想请教一下：
1. 因为是做应用，所以比较关注estimator。我们在推理的时候，能不能只用estimator？是否还得配合着imitator来用使得这个动作序列更逼真一些？用和不用imitator做推理（不是训练）在性能上差多少呢？
2. 关于整个framework，我自己理解是这三个模块结构上是可拆解替换的是吗？也就是我可以自定义修改estimator的实现，然后用pretrained的imitator和hallucinator来单独训练estimator的是吗？

**Comment by PGogo** [comment]
当然了，我做的应用是自用小工具，非商业项目。

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.

> 我们在推理的时候，能不能只用estimator？是否还得配合着imitator来用使得这个动作序列更逼真一些？用和不用imitator做推理（不是训练）在性能上差多少呢？

Yes, the [estimator_inference folder](https://github.com/Garfield-kh/PoseTriplet/tree/main/estimator_inference) is estimator only.
Indeed, the RL based imitator can perform physical correction as suggested in [PPT](https://drive.google.com/drive/folders/1oEJfnjR1NupC4SVo7_hk2wMu5BPsRBd2?usp=sharing): imitator page.
However, the imitor in my work is offline setting, if you want real-time, you need to check the previous work [SimPoE](https://arxiv.org/abs/2104.00683).
The performance difference, in my case, with imitator the artifacts is better, but the p2 is worse as physical constrain is involved, you may check other related physical aware works mentioned in  the PPT.

> 关于整个framework，我自己理解是这三个模块结构上是可拆解替换的是吗？也就是我可以自定义修改estimator的实现，然后用pretrained的imitator和hallucinator来单独训练estimator的是吗？

Yes, the framework is new, but the three modules are flexible, as long as you can link them together.
The goal of imitator and hallucinator is for plausibility and diversity, so use the pretrain or train from scratch both are okay.

One more suggestion: this work is under self-supervised setting (only use 2D data), if you want to use it for application, involve more GT 2D-3D data would be better.

**Comment by PGogo** [comment]
> One more suggestion: this work is under self-supervised setting (only use 2D data), if you want to use it for application, involve more GT 2D-3D data would be better.

为什么呢？按我的理解，imitator+hallucinator增广出来的3D数据投影成2D的数据之后，这个2D-3D pair对于estimator来说就已经是GT了呀，它甚至要比真实传感器采集的数据要更准（系统误差等）。是因为hallucinator生成的序列也是基于初始的序列，所以需要更多的初始动作增加多样性吗？

**Comment by Garfield-kh** [comment]
The projected 2D-3D pose pair can be considered as GT pairs. However, its quality is still somehow not as good as the real GT (e.g., H36M GT data), which can be seen from the performance table. 1.
so involve them will be better.

**Comment by PGogo** [comment]
了解啦，谢谢！
