### ISSUE TITLE
Original PPTX Presentation

### ISSUE THREAD

**Issue by BrianG13** [Garfield-kh/PoseTriplet#16]
Hi guys,

Love you work, super interesting!

Do you have the original PPTX file for the slide presentation posted in this repo? The uploaded one: [PPT](https://drive.google.com/drive/folders/1oEJfnjR1NupC4SVo7_hk2wMu5BPsRBd2?usp=sharing) is a PDF file.

Thanks!

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
I have put the orignal pptx in the same folder, it's about 100MB size.
