### ISSUE TITLE
no such file or directory: './data_cross/3dhp/3dhp_testset_bySub.pkl'

### ISSUE THREAD

**Issue by JiahongWu1995** [Garfield-kh/PoseTriplet#17]
Hello, I am very interesting in your excellenct work! 
When I run the code in script-summary-gt2d-v5.sh, I get the following error:
 ``` no such file or directory: './data_cross/3dhp/3dhp_testset_bySub.pkl' ```
How can I get this file?  thank you!
https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L30

**Comment by JiahongWu1995** [comment]
@Garfield-kh

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
I have uploaded the pkl file in [checkpoint folder](https://drive.google.com/drive/folders/1iGh1Sk30Tg8-UgGXM_8KwTQSbh7jcW9Y?usp=sharing).
You can use it by placing it in the estimator folder.

**Comment by JiahongWu1995** [comment]
> Hi, thank you for the interest! I have uploaded the pkl file in [checkpoint folder](https://drive.google.com/drive/folders/1iGh1Sk30Tg8-UgGXM_8KwTQSbh7jcW9Y?usp=sharing). You can use it by placing it in the estimator folder.

it would be a great help!! Thanks for your reply!!
