### ISSUE TITLE
3d prediction bad 

### ISSUE THREAD

**Issue by chunniunai220ml** [Garfield-kh/PoseTriplet#18]
HI, TAHNK for your work!
when I test the my video, some bad 3d case like this:
![捕获1](https://user-images.githubusercontent.com/17668109/183928961-414dc941-a4fa-438c-89bb-05dc77416fe7.JPG)
![捕获2](https://user-images.githubusercontent.com/17668109/183928983-cde947e4-ea6e-4794-a9c8-790a9c23b35a.JPG)

and the correspond 2D prediction:
![捕获3](https://user-images.githubusercontent.com/17668109/183929344-590923fe-1303-43e0-b801-fa9b8dc92223.JPG)

what's wrong with me?   can u give me any advice ?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
I think the order your 2D pose sequence might be wrong.
Can you check if they are in this order [start from (0) Hips, end with (15) RightHand](https://github.com/Garfield-kh/PoseTriplet/blob/8d1cfa0037923a26e510d03312916345b8d2a401/hallucinator/code_rib/bvh_skeleton/humanoid_1205_skeleton.py#L14)?
