### ISSUE TITLE
Questions about ablation study on rounds of training

### ISSUE THREAD

**Issue by JinchengWang** [Garfield-kh/PoseTriplet#19]
First, I just want to say, thank you so much for the great work, and for open-sourcing your code as well!

I was looking at the training script and noticed that it seems to contain more than 3 rounds of training, while the paper only included the results from the first 3 rounds. Have you tried more rounds of training and if so did it lead to further performance improvement?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
Yes, the performance gets better with more rounds of training.
As mentioned in [README.md](https://github.com/Garfield-kh/PoseTriplet/blob/main/README.md), we have provide a [checkpoint folder](https://drive.google.com/drive/folders/1iGh1Sk30Tg8-UgGXM_8KwTQSbh7jcW9Y?usp=sharing) for your reference. You can try it with `tensorboard --logdir=.`
