### ISSUE TITLE
  Training issue: joints' number (17) of the model is not equal to the input 2D joints' number (16) when evaluating S911, 3DHP & 3DHPW 

### ISSUE THREAD

**Issue by gyou2021** [Garfield-kh/PoseTriplet#21]
estimator/common/model.py", line 66, in forward
    assert x.shape[-2] == self.num_joints_in
AssertionError

Debug 
in def _model_preparation_pos(self) of posegan_basementclass.py
self.poses_valid_2d[0].shape[-2] is 17;   self.dataset.skeleton().num_joints() is 16.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
The experiment setting is 16 joints.
We removed the nose from [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) for cross-data evaluation, use its data folder will rise error.
You need to follow the [readme](https://github.com/Garfield-kh/PoseTriplet/blob/main/estimator/README.md) here to prepare the 16 joints one.

**Comment by gyou2021** [comment]
Hi, Thank you for your explanation!
However, when I ran the command:  CUDA_VISIBLE_DEVICES=0 python posegan_train.py --note vp_0 --add_random_cam False -e 50 -b 512 -lr 3e-4 -lrgcam 1e-4 -lrdcam 1e-4 --df 3 -k gt --dcam_choice dcam_pa1 --cam_r_range 0.5 --cam_t_range 3. --expert_dict_path ../imitator/checkpoint/exp_h36m_gt2d_v5/helix_0/results/posemimic/subject_h36m_helix_0/results/iter_0900_train_naivefs.p --checkpoint ./checkpoint/exp_h36m_gt2d_v5/helix_0/results/posemimic/subject_h36m_helix_0/results/iter_0900_train_naivefs
the above error occurs.
I think in def keypoints_preparation(self),
when loading data_2d_h36m_gt.npz, since the number of its 2D joints is 17,  codes like the following should be executed to change 17 joints to 16 joints, right?
          self.keypoints = convert_AlphaOpenposeCoco_to_standard16Joint(
                               self.keypoints.copy())  # Nx16x2
        self.keypoints_imgunnorm = self.keypoint_square_padding(self.keypoints)

because self.remove_joints([4, 5, 9, 10, 11, 14, 16, 20, 21, 22, 23, 24, 28, 29, 30, 31])
            left joints are 0,1,2,3,6,7,8,12,13,15,17,18,19,25,26,27, that is 14 should be removed from 17 2D joints, or keypoints[9] should be removed from the 2D joints, right? 
standart_16joint = np.delete(standart_17joint, 9, axis=1)
the standart_16point is as the follows, right?
![image](https://user-images.githubusercontent.com/96715186/193466134-78653c45-cb04-4b3e-a8cb-fdceb4a697a6.png)

**Comment by Garfield-kh** [comment]
Hi, 
the prepared data from [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) is 17 joint setting for both 2D and 3D npy file.
If you follow the [readme](https://github.com/Garfield-kh/PoseTriplet/blob/main/estimator/README.md), which is copyed from [PoseAug](https://github.com/jfzhang95/PoseAug) and [SemGCN](https://github.com/garyzhao/SemGCN), the data_2d_h36m_gt.npz will be 16 joints.

If you would like to modify the function to convert from 17 to 16, you just need to check if the joint definition of 16-joint is the same as this order [start from (0) Hips, end with (15) RightHand](https://github.com/Garfield-kh/PoseTriplet/blob/8d1cfa0037923a26e510d03312916345b8d2a401/hallucinator/code_rib/bvh_skeleton/humanoid_1205_skeleton.py#L14).

**Comment by gyou2021** [comment]
It works. Thank you!
