### ISSUE TITLE
How to check take_599 Hip flip in training

### ISSUE THREAD

**Issue by gyou2021** [Garfield-kh/PoseTriplet#22]
Hi, 
In the training of helix 0,  
>>check if the take_599 Hip flip, if flip, maybe not a good initialization.
How to check it? Is it to check h36m_take_599.bvh ?  Could you show a 'Hip flip' example?   
"if flip, maybe not a good initialization.", why?
Thank you.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
You can view the result by [pose_imitation/vis_pose.py](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L46) after run the [bvh to qpos](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L44)

**Comment by gyou2021** [comment]
Thank you! I'll try it.
