### ISSUE TITLE
Posegan_train 

### ISSUE THREAD

**Issue by gyou2021** [Garfield-kh/PoseTriplet#25]
Hi, In imitator/script-summary-gt2d-v5.sh, since  182 # use default setting #5 if it dose not crash, why should we run posegan_train.py four times from line 175 -180? It seems each posegan_train.py is independent of others.  Is it right that we only run 177 CUDA_VISIBLE_DEVICES=0 python posegan_train.py --note vp_5_wrib --add_random_cam...? Thank you.

**Comment by Garfield-kh** [comment]
Yes, `vp_5_wrib` is enough in this step.
It is just some time I meet issue that in the next round, the RL physical correction crashed with NAN value, then I get back and take another one to continue.

**Comment by gyou2021** [comment]
Thank you!
