### ISSUE TITLE
The parameter value of pose_mimic_eval.py

### ISSUE THREAD

**Issue by gyou2021** [Garfield-kh/PoseTriplet#26]
Hi, 
In imitator/script-summary-gt2d-v5.sh,
159 >> inference the RL result using trained model 
160 python pose_imitation/pose_mimic_eval.py --cfg subject_h36mrib --data train --num-threads 52 --iter 1200 ..... 
Why 1200 was selected for --iter? How to select the value? Thank you!

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
in this part, you can see that I use the this line [157](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/imitator/script-summary-gt2d-v5.sh#L157) to copy the previous RL training weight to here and rename it as iter_100.p as a pretraining.
In this way, the training iteration can be reduced. 
This can be verified by looking at the tensorboard training curve, the total reward.
1200 is set for one night training, I also tried 2400, 3000, 6000, they produce similar result.

**Comment by gyou2021** [comment]
Thank you for your reply!
