### ISSUE TITLE
Result on H36M

### ISSUE THREAD

**Issue by gyou2021** [Garfield-kh/PoseTriplet#27]
Hi, in your paper, PoseTriplet result is 68.2 on H36M in terms of MPJPE (P1), P2 45.1 using GT 2d pose. I viewed your training result. Is the 68.2 from s911_flip_p1 (tag: eval_P_epoch_real/s911_flip_p1)? However, I found smaller values on the graph. Where are the P1 results for 3DHP and 3DPW from? (from eval_P_epoch_real?) Thank you!

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
As mentioned in issue #19 and also [PPT](https://drive.google.com/drive/folders/1oEJfnjR1NupC4SVo7_hk2wMu5BPsRBd2?usp=sharing), the performance is just keeping improving through round of training.
The result paper report is a short training time with smaller rounds.
And if you check the time of training curve, it takes one month for that better result (around 50 in P1 with vi).
I was even wondering if it can reach the performance of supervised approach (videopose: 40 P1 in H36M).
Yes, all result are take from tag: eval_P_epoch_real/flip.
![image](https://user-images.githubusercontent.com/37209147/198160651-7f7eb48a-0549-460c-8f19-5c1f77f0ee67.png)

**Comment by gyou2021** [comment]
I see. Thank you for your detailed explanation and your great work!
