### ISSUE TITLE
Regarding the distance between the camera and the subject

### ISSUE THREAD

**Issue by jin-tmoya** [Garfield-kh/PoseTriplet#28]
Hi,Mr. Garfield-kh.
Sorry, I have to post a new issue.

This may be  fundamental question, but is there any particular distance between the subject and the camera that is required for this system to accurately produce a 3D image?
I am wondering if it has something to do with the "4m" that Mr. Garfield-kh mentioned.

Also, I feel that the 3D estimation is worse when the subject is a child.Do you know of any way to adjust it?

Thank you.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
I am not sure what you mean the '4m' is.
"**but is there any particular distance between the subject and the camera that is required for this system to accurately produce a 3D image?**"
- Yes, as this is a model trained with training data, and if you check the training dataset [Human3.6M](https://vision.imar.ro/human3.6m/pami-h36m.pdf), you will see that the camera view, camera distance, subject body size, all are restricted in a small range. This means model trained with such data, will performance well on test video which lay in the same destribution of "amera view, camera distance, subject body size".

"**I feel that the 3D estimation is worse when the subject is a child.Do you know of any way to adjust it?**"
- You can try train a new model by replace the skeleton size of training data as children to get a children pose estimation model which specificlly focus on children.

**Comment by jin-tmoya** [comment]
Thanks for the reply. Sorry, "4m" is 4 meter.

Do you know the best value for each of "camera view, camera distance, subject body size"? If you know, please let us know.

Or, if you have any experience of getting good results if the camera distance is about this much and the subject is in this condition, we would appreciate it if you could tell us about it.

**Comment by Garfield-kh** [comment]
Hi, this is about pose data augmentation, which you need to augment the existing data to be as similar as possible to you test case, so that it can perform well on your specific test data.
You may refer to the papers: 
[AdaptPose](https://openaccess.thecvf.com/content/CVPR2022/papers/Gholami_AdaptPose_Cross-Dataset_Adaptation_for_3D_Human_Pose_Estimation_by_Learnable_CVPR_2022_paper.pdf)
[PoseAug](https://arxiv.org/pdf/2105.02465.pdf)

**Comment by jin-tmoya** [comment]
Thank you very much.
I will check it out.
