### ISSUE TITLE
Causal model?

### ISSUE THREAD

**Issue by noahcoolboy** [Garfield-kh/PoseTriplet#32]
Hello! First of all, I would like to thank you for your work.

I'm interested in running this model in real-time from a webcam / live video stream.
However, I believe this model uses both future and past frames.
Would I have to retrain the model from scratch with access to only past frames to predict the current pose, or is a pretrained causal model already available? And how would it be used / trained? Would it be by setting the causal shift to the pad value?

Thanks!

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!

As this framework is combined with pose estimation and imitation.
If you are interested in pose estimation in casual, I think the [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) casual setting or [mmpose](https://github.com/open-mmlab/mmpose) is what you are looking for.
If you are interested in pose imitation in casual, I think [EmbodiedPose](https://github.com/KlabCMU/EmbodiedPose) maybe match.

Thanks~

**Comment by noahcoolboy** [comment]
Thank you!
