### ISSUE TITLE
About the Annotation Paradigm

### ISSUE THREAD

**Issue by davidpengiupui** [Garfield-kh/PoseTriplet#33]
Thank you so much for your project! I notice that the datasets you used are almost the same as works like VideoPose3D, but their datasets include 17 keypoints, while yours include 16 keypoints. I compared them and found one joint on the head is removed, i.e., they annotate 2 joints on the head while you annotate 1 joint. May I know which one you removed? The upper one on the top of the skeleton or the lower one near the neck?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
We use 16 joints (removed Neck/Nose) in H36M following previous work SemGCN.
You may check for more detail [here](https://github.com/jfzhang95/PoseAug/issues/4#issuecomment-860355377) for why use 16 joints.

**Comment by davidpengiupui** [comment]
Thank you so much for your response!
