### ISSUE TITLE
3DHP and 3DPWD dataset preprocessing

### ISSUE THREAD

**Issue by wd-hub** [Garfield-kh/PoseTriplet#34]
Thanks for your wonderful work, I came up with the data problem when training estimator:
'./data_cross/3dhp/3dhp_testset_bySub.pkl' and './data_cross/3dpw/3dpw_testset_bySub.pkl' is not exist, how can I get the two files?
Looking forward for your replay, thanks.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest and sorry for the late reply.
I found that this was mentioned in previous [issue 17](https://github.com/Garfield-kh/PoseTriplet/issues/17#issuecomment-1208973145).
Hope it helps.

**Comment by wd-hub** [comment]
Thanks a lot for your reply! Another question:
I trained the imitator following the given steps and tested it with some wild videos. It works well in most cases, but could not imitate the jumping motion. Is it due to the lack of jumping training data? Or some further modifications required for jumping imitation.
Thanks!

**Comment by Garfield-kh** [comment]
Hi, in the pose to bvh conversion [code ](https://github.com/Garfield-kh/PoseTriplet/blob/eb93132f99161bd776dafbcb713e9fb43e501c36/estimator/posegan_evaluate.py#L360), I made the lowerest point as ground for every frame. You may change here (e.g., use the lowerest point of the whole motion sequence as ground) to get the jump action.
