### ISSUE TITLE
Can this model inference single image?

### ISSUE THREAD

**Issue by tiger990111** [Garfield-kh/PoseTriplet#5]
I want to find out whether this model can inference online.
So does it need the frame from future when it inference current frames?
or like the question as title, can this model inference single image?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!

> So does it need the frame from future when it inference current frames?

The released estimator model is [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) with 
`temporal window frames = 27`
`causal = False`
This means it takes the previous 13 frames and furture 13 frames for current frame pose estimation.

> I want to find out whether this model can inference online.

If you set the `causal` to be `True `during model training, it is then online setting.

> can this model inference single image?

If you set the `temporal window frames = 1`, then it is a single frame model.

**Comment by tiger990111** [comment]
I didn't change anything including what you mentioned above. 
I simply extract one frame of `self.keypoints` by 
`npz = np.load(args.input_npz)
self.keypoints = npz['kpts']  # (N, 17, 2) - coco format
self.keypoints = self.keypoints[[120]]`
which i finally extract the 120th frame.
And i set to save as .gif
Finally I get the result of that one frame animation.
So what is the difference between the result i have gotten and the result i would get if i followed your tutorial?

**Comment by tiger990111** [comment]
And...I think there is no `temporal window frames = 27` in your code, doesn't it ?

**Comment by Garfield-kh** [comment]
Here is the model setting [args.architecture](https://github.com/Garfield-kh/PoseTriplet/blob/eb0ce5a776c2691bc321fb9726c845acd531d597/estimator_inference/videopose-j16-wild-eval_run.py#L267).
`args.architecture = '3,3,3'` => ` temporal window frames = 27`.

> Finally I get the result of that one frame animation.

This is because the `dataloader `will automaticlly padding the sequence (even the sequence length=1) 13 frames before start and 13 frames after the endding. This makes it looks like predict a single frame result.

**Comment by tiger990111** [comment]
OHHH, thanks for your explanation!
so if i want to set `temporal window frames = 1`, I should set args.architecture = '1,1,1' right?
And i have another question:
My video is 790 frames, but the 2dkpts predicted is as the shape of `(778, 17, 2)` .
So why the number of frame is unmatch?

**Comment by tiger990111** [comment]
well ,`args.architecture = '1,1,1' ` will raise error:

```
-------------- prepare video clip spends 0.05 seconds
-------------- load keypoint spends 0.01 seconds
Loading checkpoint ./checkpoint/ckpt_ep_045.bin
Traceback (most recent call last):
  File "videopose-j16-wild-eval_run.py", line 298, in <module>
    Vis.redering()
  File "videopose-j16-wild-eval_run.py", line 39, in redering
    result = self.get_prediction(architecture, self.ckpt_path)
  File "videopose-j16-wild-eval_run.py", line 145, in get_prediction
    model_pos = self._get_model(architecture, ckpt_path)
  File "videopose-j16-wild-eval_run.py", line 164, in _get_model
    model_pos.load_state_dict(checkpoint['model_pos'])
  File "/data/kwt/anaconda3/envs/triplet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in loa
d_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TemporalModel:
        size mismatch for expand_conv.weight: copying a param with shape torch.Size([1024, 32, 3]) from checkpoint,
 the shape in current model is torch.Size([1024, 32, 1]).
        size mismatch for layers_conv.0.weight: copying a param with shape torch.Size([1024, 1024, 3]) from checkpo
int, the shape in current model is torch.Size([1024, 1024, 1]).
        size mismatch for layers_conv.2.weight: copying a param with shape torch.Size([1024, 1024, 3]) from checkpo
int, the shape in current model is torch.Size([1024, 1024, 1]).
```

**Comment by Garfield-kh** [comment]
> My video is 790 frames, but the 2dkpts predicted is as the shape of (778, 17, 2) .

This one I am not sure, should be somewhere about the 2D detector.

> well ,`args.architecture = '1,1,1'` will raise error:

`args.architecture = '1,1,1'` will be a single frame model, however, this should be done in both training and inference.
This means the `multi-frame (3,3,3) model` cannot be loaded as `single-frame (1,1,1) model` .

**Comment by tiger990111** [comment]
Ok, I got you!

**Comment by liuhaorandezhanghao** [comment]
> Hi, thank you for the interest!
> 
> > So does it need the frame from future when it inference current frames?
> 
> The released estimator model is [VideoPose3D](https://github.com/facebookresearch/VideoPose3D) with `temporal window frames = 27` `causal = False` This means it takes the previous 13 frames and furture 13 frames for current frame pose estimation.
> 
> > I want to find out whether this model can inference online.
> 
> If you set the `causal` to be `True `during model training, it is then online setting.
> 
> > can this model inference single image?
> 
> If you set the `temporal window frames = 1`, then it is a single frame model.

hi,thanks for your greeting work,and my question is if i want to inference online using an usb camera,i must set causal to be true and retrain the model?i can't use the existing model?

**Comment by chunniunai220ml** [comment]
> > My video is 790 frames, but the 2dkpts predicted is as the shape of (778, 17, 2) .
> 
> This one I am not sure, should be somewhere about the 2D detector.
> 
> > well ,`args.architecture = '1,1,1'` will raise error:
> 
> `args.architecture = '1,1,1'` will be a single frame model, however, this should be done in both training and inference. This means the `multi-frame (3,3,3) model` cannot be loaded as `single-frame (1,1,1) model` .

if i want to inference one image ,i must set causal to be true and retrain the model?
is there a pretrained model with 'args.architecture = '1,1,1'`?
