### ISSUE TITLE
Lower body skeleton issue

### ISSUE THREAD

**Issue by Abi5678** [Garfield-kh/PoseTriplet#6]
Hi I am trying to get the 3 pose on upper body and is there a way to filter or remove lower body keypoints completely. I am getting the following output where the legs are distorted but I don't want lower body joints to be visible in my output. 

<img width="1088" alt="Screen Shot 2022-04-25 at 2 23 37 PM" src="https://user-images.githubusercontent.com/44240456/165562671-e89730f0-ff80-4b51-845f-124f87be481a.png">

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
If you just want to remove it from output, you may change the plot funtion in [render_animation](https://github.com/Garfield-kh/PoseTriplet/blob/eb0ce5a776c2691bc321fb9726c845acd531d597/estimator_inference/videopose-j16-wild-eval_run.py#L228).
If you are intereted in occlusion case pose estimation, then you will need occlusion augmentation during training, or some optimization like this work [GLAMR](https://nvlabs.github.io/GLAMR/).

**Comment by Abi5678** [comment]
Hi, thanks for the response. Can you describe what needs to be modified. I am a bit confused as I am new to 3D pose estimation.

**Comment by Garfield-kh** [comment]
Maybe you can just replace the position value of lower body joint by left/right hip, then it will not be plot out.
Here are the joint definition for 16 joints:
`'Hips': 0,
            'RightUpLeg': 1,
            'RightLeg': 2,
            'RightFoot': 3,
            'LeftUpLeg': 4,
            'LeftLeg': 5,
            'LeftFoot': 6,
            'Spine2': 7,
            'Neck': 8,
            'Head': 9,
            'LeftArm': 10,
            'LeftForeArm': 11,
            'LeftHand': 12,
            'RightArm': 13,
            'RightForeArm': 14,
            'RightHand': 15,`

**Comment by Abi5678** [comment]
Thanks so much finally I was able to get this work. Great work and appreciate the help.
