### ISSUE TITLE
The depth info of legs is always bad

### ISSUE THREAD

**Issue by tiger990111** [Garfield-kh/PoseTriplet#8]
I found that the depth of leg is always different from other parts, which leads to lean-forward bad case.
Like, this is my kpts2d on img,
![kpt2d](https://user-images.githubusercontent.com/54582916/165885814-8de39211-9501-4ada-a6ef-aeee371aecd9.png)

And this is the result of PoseTriplet, printed with 
`ax.view_init(0, 70)` and `ax.view_init(0, 0)`
![kpts3d](https://user-images.githubusercontent.com/54582916/165885872-1631f29d-dec3-4726-b7be-971a2cde0076.png)

So, Have you found this issue when you research in this task? Would you give me some advise to avoid those bad cases?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
I think the image is not 1:1 here. 
As the model is train with H36M dataset, the model will think every 2D/3D skeleton is under similar bone length ratio as its training data.
If the ratio of 2D pose does not match, the model will try to guess it in someway such that the result meets its memory(i.e. training data).
Maybe two possible approaches:
1. Scale the image to similar ratio as the training data. (also try scale down the 2D pose to make it like the person is not so close to the camera)
2. train a new pose model with the scale ratio as this input camera.
